name: first workflow
on:
 workflow_dispatch:
jobs:
 firstjob:
   runs-on: self-hosted
   steps:
   - name: firstJob script
     shell: cmd 
     run: Write-Host 'Hello World! This is the first job.'

 secondjob:
   runs-on: ubuntu-latest
   steps:
   - name: secondJob script
     shell: bash
     run: |
      echo this is the second job
      echo and this is a multi-line script
